# Generated by Django 2.0.2 on 2018-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_ticket', models.CharField(max_length=255, unique=True)),
                ('artifact_path', models.CharField(max_length=255)),
                ('assignee_bank_id', models.IntegerField()),
                ('remedy_cr_number', models.CharField(max_length=255)),
                ('rundeck_job_id', models.CharField(max_length=255)),
                ('rundeck_log_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rundeck_status', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
